---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wplite
  namespace: default
  labels:
    layer: wplite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi