---
apiVersion: v1
kind: Service
metadata:
  name: wplite
  namespace: default
  labels:
    app: wplite
spec:
  type: ClusterIP
  selector:
    app: wplite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http