name: build and deploy to s3
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      release-id:
        description: 'Release ID'
        required: false

jobs:   
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install wplite cli
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: robertlestak/wplite
        extension-matching: disable
        rename-to: wplite
        chmod: 0755
    - name: build
      run: wplite build
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: 'wp-content/static'
    - name: invalidate cloudfront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}